# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. You can
  reopen it by adding a comment to this issue.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it has not had recent activity.
  If you are the owner of this issue, you can either re-open it and provide a more
  complete description; or create a new issue.
  Thank you for your contributions.
# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true  
# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: true
