default_stages: [pre-commit, pre-push]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint-docker
        args:
          - --config=docs/.markdownlint.yaml
          - --ignore=docs/api/gef.md
          - --ignore=docs/obsolete/docs/index.md
          - --ignore=docs/index.md
          - --ignore=README.md
          - "docs/**/*.md"
