name: Bug Report
description: Help us improve GEF by filling up this report correctly.
title: "[Bug] "
body:
- type: input
  attributes:
    label: GEF Version
    description: |
      The exact version of GEF.
    placeholder: X.X.X
  validations:
    required: true
- type: input
  attributes:
    label: GDB Version + Python
    description: |
      The version of GDB and Python you're using
    placeholder: X.X.X
  validations:
    required: true     
- type: textarea
  attributes:
    label: What's the issue you encountered?
    description: |
      Describe the issue in detail and what you were doing beforehand.
  validations:
    required: true
- type: textarea
  attributes:
    label: How can the issue be reproduced?
    description: Include a detailed step by step process for recreating your issue.
  validations:
    required: true
- type: textarea
  attributes: 
    label: GEF Version
    description: |
      Use the `version` command to populate this field
    placeholder: X.X.X
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Architecture impacted
    options:
    - label: x86
    - label: x64
    - label: ARM
    - label: ARM64
    - label: MIPS
    - label: MIPS64
    - label: PPC
    - label: PPC64
- type: textarea
  attributes:
    label: Describe your issue
    value: |
      Provide a step-by-step to reproduce your issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Minimalist test case
    value: |
      Use this field for a minimal code to compile and spot the issue:     
      ```c
      // compile with gcc -fPIE -pic -o my_issue.out my_issue.c
      int main(){ return 0; }
      ```
      You can also provide a Dockerfile if you prefer
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context ?
    value: |
      - Screenshots
      - Callstack
      - Coredumps
      - If possible and useful, please upload the binary
  validations:
    required: false
